ebertti/awesome-telegram

- README.md
> Add Telegraf

- README.md
Because group about macOS in Russian
> @proMacOS -> @macOS_ru

- README.md
This bot is for all those people who suffer from telegram over-stickering
> Add @nosticker_bot

- README.md
I would like to integrate my own **C++** Telegram Bot API wrapper within this awesome list.
Thanks!
> Added telegram-bot-api C++ project

- README.md
https://github.com/dizballanze/m00dbot
> Add m00dbot

- README.md
This is telegram bot constructor from command-line.
> Added shell2telegram

- README.md
Added curated list of Uzbek Telegram dev groups for those who speak in Uzbek
> Added awsome-telegram-dev-groups-uz

- README.md
> Adding Telegram Directory

- README.md
InviteMember (https://invitemember.com) — membership bot platform for paid Telegram channels and groups
> Add InviteMember

- README.md
https://github.com/pengrad/java-telegram-bot-api
> Add java-telegram-bot-api library

- README.md
Added [Tourmaline](https://github.com/watzon/tourmaline). A Telegram bot API wrapper written in [Crystal](https://crystal-lang.org).
> Added Tourmaline - Telegram bot API wrapper

- README.md
I recently wrote to the creator of the repository, and he was not against the new section. Well done. 😉
> Added themes section for telegram.

- README.md
I've added bot for playing tic-tac-toe in **Games** category.
> Add bot for playing tic-tac-toe game

- README.md
We had opensourced first in the world mtproto package on golang (literally, first one), so want to share this info to everyone :smirk:
> Added MTProto package for Golang

- README.md
Also included additions from conflicted pull requests
> added two python and one go library 

- README.md
Add a new PHP 8 Telegram library.
> Add PHP library

- README.md
Hide This Bot's source code: https://github.com/undrcrxwn/hidethisbot
> Add Hide This Bot to Inline Bots category

- README.md
[gotd ](github.com/gotd/td)is a pure Go MTProto client
> Add github.com/gotd/td

- README.md
#63 has added #24, Removing #24. Duplicated
Fix formatting for `*` vs `+`
Remove `ts-telegraf-decorators` https://github.com/panarama360/ts-telegraf-decorators hasn't been updated for 15months. Telegraf has its own typings now.
Add `telegram-id` https://github.com/GabrielRF/telegram-id Guide on how to get Telegram IDs
Add another awesome list
> Remove #24. Update libs. Add guide/directory

- README.md
Client Api Library For C# .
https://github.com/wiz0u/WTelegramClient
> adding WTelegramClient

- README.md
Repo Link: https://github.com/AnyTimeTraveler/telegram-menu-library
> Add telegram-menu-library to the Java libraries

- README.md
Coding at Night is a Telegram channel where technology related news & tools are shared on a daily basis.
> Add Coding at Night Telegram Channel

- README.md
Client Api library for PHP 
https://github.com/danog/MadelineProto
still cant believe this wasn't already in the list 😮
> adding MadeLineProto

- README.md
> Update README.md for new bot

- README.md
[Kubernative](https://t.me/kubernative) is a new Telegram channel that shares tools, articles, and news about Kubernetes and the Cloud Native ecosystem.
> Add Kubernative channel

- README.md
[Awesome DevOps Telegram](https://github.com/palark/awesome-devops-telegram) is a GitHub repo listing English-speaking Telegram groups and chats for DevOps and SRE engineers.
> Add Awesome DevOps Telegram

- README.md
Seems like @savevideobot has been removed/hidden:
> Remove @savevideobot

- README.md
Hi, I added the @HyperTAG_bot to the list of bots. 
Thanks for your great job!
> Added HyperTAG Bot

- README.md
This is a pull request to add Groupfind to the telegram directory section.
> Add groupfind.org telegram directory

- README.md
> Add GramIO as TypeScript bot library

- README.md
A lightweight CLI utility to send messages and media files to Telegram chats and channels — directly from your terminal.
https://github.com/beeyev/telegram-owl/
> Add new tool: beeyev/telegram-owl
